/*
 * Copyright (C) 2014 INRIA
 *
 * This file is subject to the terms and conditions of the GNU Lesser
 * General Public License v2.1. See the file LICENSE in the top level
 * directory for more details.
 */

/**
 * @ingroup     drivers_atmegarfr2
 * @{
 *
 * @file
 * @brief       Register and command definitions for the ATMEGARFR2 radio
 *
 */

#ifndef AT86ATMEGARFR2_SETTINGS_H
#define AT86ATMEGARFR2_SETTINGS_H

#ifdef __cplusplus
extern "C" {
#endif

#define ATMEGARFR2_RX_BUF_SIZE   3

/*
enum atmegarfr2_access {
    ATMEGARFR2_ACCESS_REG = 0x80,
    ATMEGARFR2_ACCESS_FRAMEBUFFER = 0x20,
    ATMEGARFR2_ACCESS_SRAM = 0x00,

    ATMEGARFR2_ACCESS_READ = 0x00,
    ATMEGARFR2_ACCESS_WRITE = 0x40,
};
*/

enum atmegarfr2_register {
    ATMEGARFR2_REG__TRX_STATUS = 0x01,
    ATMEGARFR2_REG__TRX_STATE = 0x02,
    ATMEGARFR2_REG__TRX_CTRL_0 = 0x03,
    ATMEGARFR2_REG__TRX_CTRL_1 = 0x04,
    ATMEGARFR2_REG__PHY_TX_PWR = 0x05,
    ATMEGARFR2_REG__PHY_RSSI = 0x06,
    ATMEGARFR2_REG__PHY_ED_LEVEL = 0x07,
    ATMEGARFR2_REG__PHY_CC_CCA = 0x08,
    ATMEGARFR2_REG__CCA_THRES = 0x09,
    ATMEGARFR2_REG__RX_CTRL = 0x0A,
    ATMEGARFR2_REG__SFD_VALUE = 0x0B,
    ATMEGARFR2_REG__TRX_CTRL_2 = 0x0C,
    ATMEGARFR2_REG__ANT_DIV = 0x0D,
    ATMEGARFR2_REG__IRQ_MASK = 0x0E,
    ATMEGARFR2_REG__IRQ_STATUS = 0x0F,
    ATMEGARFR2_REG__VREG_CTRL = 0x10,
    ATMEGARFR2_REG__BATMON = 0x11,
    ATMEGARFR2_REG__XOSC_CTRL = 0x12,

    ATMEGARFR2_REG__RX_SYN = 0x15,

    ATMEGARFR2_REG__XAH_CTRL_1 = 0x17,
    ATMEGARFR2_REG__FTN_CTRL = 0x18,

    ATMEGARFR2_REG__PLL_CF = 0x1A,
    ATMEGARFR2_REG__PLL_DCU = 0x1B,
    ATMEGARFR2_REG__PART_NUM = 0x1C,
    ATMEGARFR2_REG__VERSION_NUM = 0x1D,
    ATMEGARFR2_REG__MAN_ID_0 = 0x1E,
    ATMEGARFR2_REG__MAN_ID_1 = 0x1F,
    ATMEGARFR2_REG__SHORT_ADDR_0 = 0x20,
    ATMEGARFR2_REG__SHORT_ADDR_1 = 0x21,
    ATMEGARFR2_REG__PAN_ID_0 = 0x22,
    ATMEGARFR2_REG__PAN_ID_1 = 0x23,

    ATMEGARFR2_REG__IEEE_ADDR_0 = 0x24,
    ATMEGARFR2_REG__IEEE_ADDR_1 = 0x25,
    ATMEGARFR2_REG__IEEE_ADDR_2 = 0x26,
    ATMEGARFR2_REG__IEEE_ADDR_3 = 0x27,
    ATMEGARFR2_REG__IEEE_ADDR_4 = 0x28,
    ATMEGARFR2_REG__IEEE_ADDR_5 = 0x29,
    ATMEGARFR2_REG__IEEE_ADDR_6 = 0x2A,
    ATMEGARFR2_REG__IEEE_ADDR_7 = 0x2B,

    ATMEGARFR2_REG__XAH_CTRL_0 = 0x2C,
    ATMEGARFR2_REG__CSMA_SEED_0 = 0x2D,
    ATMEGARFR2_REG__CSMA_SEED_1 = 0x2E,
    ATMEGARFR2_REG__CSMA_BE = 0x2F,


    ATMEGARFR2_REG__TST_CTRL_DIGI = 0x36,
};

enum {
    ATMEGARFR2_TRX_CTRL_0_MASK__PAD_IO = 0xC0,
    ATMEGARFR2_TRX_CTRL_0_MASK__PAD_IO_CLKM = 0x30,
    ATMEGARFR2_TRX_CTRL_0_MASK__CLKM_SHA_SEL = 0x08,
    ATMEGARFR2_TRX_CTRL_0_MASK__CLKM_CTRL = 0x07,

    ATMEGARFR2_TRX_CTRL_0_DEFAULT__PAD_IO = 0x00,
    ATMEGARFR2_TRX_CTRL_0_DEFAULT__PAD_IO_CLKM = 0x10,
    ATMEGARFR2_TRX_CTRL_0_DEFAULT__CLKM_SHA_SEL = 0x08,
    ATMEGARFR2_TRX_CTRL_0_DEFAULT__CLKM_CTRL = 0x01,

    ATMEGARFR2_TRX_CTRL_0_CLKM_CTRL__OFF = 0x00,
    ATMEGARFR2_TRX_CTRL_0_CLKM_CTRL__1MHz = 0x01,
    ATMEGARFR2_TRX_CTRL_0_CLKM_CTRL__2MHz = 0x02,
    ATMEGARFR2_TRX_CTRL_0_CLKM_CTRL__4MHz = 0x03,
    ATMEGARFR2_TRX_CTRL_0_CLKM_CTRL__8MHz = 0x04,
    ATMEGARFR2_TRX_CTRL_0_CLKM_CTRL__16MHz = 0x05,
    ATMEGARFR2_TRX_CTRL_0_CLKM_CTRL__250kHz = 0x06,
    ATMEGARFR2_TRX_CTRL_0_CLKM_CTRL__62_5kHz = 0x07,
};

enum {
    ATMEGARFR2_TRX_CTRL_1_MASK__PA_EXT_EN = 0x80,
    ATMEGARFR2_TRX_CTRL_1_MASK__IRQ_2_EXT_EN = 0x40,
    ATMEGARFR2_TRX_CTRL_1_MASK__TX_AUTO_CRC_ON = 0x20,
    ATMEGARFR2_TRX_CTRL_1_MASK__RX_BL_CTRL = 0x10,
    ATMEGARFR2_TRX_CTRL_1_MASK__SPI_CMD_MODE = 0x0C,
    ATMEGARFR2_TRX_CTRL_1_MASK__IRQ_MASK_MODE = 0x02,
    ATMEGARFR2_TRX_CTRL_1_MASK__IRQ_POLARITY = 0x01,
};

enum {
    ATMEGARFR2_TRX_CTRL_2_MASK__RX_SAFE_MODE = 0x80,
    ATMEGARFR2_TRX_CTRL_2_MASK__OQPSK_DATA_RATE = 0x03,
};

enum {
    ATMEGARFR2_IRQ_STATUS_MASK__BAT_LOW = 0x80,
    ATMEGARFR2_IRQ_STATUS_MASK__TRX_UR = 0x40,
    ATMEGARFR2_IRQ_STATUS_MASK__AMI = 0x20,
    ATMEGARFR2_IRQ_STATUS_MASK__CCA_ED_DONE = 0x10,
    ATMEGARFR2_IRQ_STATUS_MASK__TRX_END = 0x08,
    ATMEGARFR2_IRQ_STATUS_MASK__RX_START = 0x04,
    ATMEGARFR2_IRQ_STATUS_MASK__PLL_UNLOCK = 0x02,
    ATMEGARFR2_IRQ_STATUS_MASK__PLL_LOCK = 0x01,
};

enum atmegarfr2_trx_status {
    ATMEGARFR2_TRX_STATUS_MASK__CCA_DONE = 0x80,
    ATMEGARFR2_TRX_STATUS_MASK__CCA_STATUS = 0x40,
    ATMEGARFR2_TRX_STATUS_MASK__TRX_STATUS = 0x1F,

    ATMEGARFR2_TRX_STATUS__P_ON = 0x00,
    ATMEGARFR2_TRX_STATUS__BUSY_RX = 0x01,
    ATMEGARFR2_TRX_STATUS__BUSY_TX = 0x02,
    ATMEGARFR2_TRX_STATUS__RX_ON = 0x06,
    ATMEGARFR2_TRX_STATUS__TRX_OFF = 0x08,
    ATMEGARFR2_TRX_STATUS__PLL_ON = 0x09,
    ATMEGARFR2_TRX_STATUS__SLEEP = 0x0F,
    ATMEGARFR2_TRX_STATUS__BUSY_RX_AACK = 0x11,
    ATMEGARFR2_TRX_STATUS__BUSY_TX_ARET = 0x12,
    ATMEGARFR2_TRX_STATUS__RX_AACK_ON = 0x16,
    ATMEGARFR2_TRX_STATUS__TX_ARET_ON = 0x19,
    ATMEGARFR2_TRX_STATUS__RX_ON_NOCLK = 0x1C,
    ATMEGARFR2_TRX_STATUS__RX_AACK_ON_NOCLK = 0x1D,
    ATMEGARFR2_TRX_STATUS__BUSY_RX_AACK_NOCLK = 0x1E,
    ATMEGARFR2_TRX_STATUS__STATE_TRANSITION_IN_PROGRESS = 0x1F,
};

enum atmegarfr2_trx_state {
    ATMEGARFR2_TRX_STATE_MASK__TRAC = 0xe0,

    ATMEGARFR2_TRX_STATE__NOP = 0x00,
    ATMEGARFR2_TRX_STATE__TX_START = 0x02,
    ATMEGARFR2_TRX_STATE__FORCE_TRX_OFF = 0x03,
    ATMEGARFR2_TRX_STATE__FORCE_PLL_ON = 0x04,
    ATMEGARFR2_TRX_STATE__RX_ON = 0x06,
    ATMEGARFR2_TRX_STATE__TRX_OFF = 0x08,
    ATMEGARFR2_TRX_STATE__PLL_ON = 0x09,
    ATMEGARFR2_TRX_STATE__RX_AACK_ON = 0x16,
    ATMEGARFR2_TRX_STATE__TX_ARET_ON = 0x19,

    ATMEGARFR2_TRX_STATE__TRAC_SUCCESS = 0x00,
    ATMEGARFR2_TRX_STATE__TRAC_SUCCESS_DATA_PENDING = 0x20,
    ATMEGARFR2_TRX_STATE__TRAC_SUCCESS_WAIT_FOR_ACK = 0x40,
    ATMEGARFR2_TRX_STATE__TRAC_CHANNEL_ACCESS_FAILURE = 0x60,
    ATMEGARFR2_TRX_STATE__TRAC_NO_ACK = 0xa0,
    ATMEGARFR2_TRX_STATE__TRAC_INVALID = 0xe0,
};

enum atmegarfr2_phy_cc_cca {
    ATMEGARFR2_PHY_CC_CCA_MASK__CCA_REQUEST = 0x80,
    ATMEGARFR2_PHY_CC_CCA_MASK__CCA_MODE = 0x60,
    ATMEGARFR2_PHY_CC_CCA_MASK__CHANNEL = 0x1F,

    ATMEGARFR2_PHY_CC_CCA_DEFAULT__CCA_MODE = 0x20,
};

enum atmegarfr2_phy_tx_pwr {
    ATMEGARFR2_PHY_TX_PWR_MASK__PA_BUF_LT = 0xC0,
    ATMEGARFR2_PHY_TX_PWR_MASK__PA_LT = 0x30,
    ATMEGARFR2_PHY_TX_PWR_MASK__TX_PWR = 0x0F,

    ATMEGARFR2_PHY_TX_PWR_DEFAULT__PA_BUF_LT = 0xC0,
    ATMEGARFR2_PHY_TX_PWR_DEFAULT__PA_LT = 0x00,
    ATMEGARFR2_PHY_TX_PWR_DEFAULT__TX_PWR = 0x00,

    ATMEGARFR2_PHY_TX_PWR_TX_PWR_VALUE__3dBm = 0x00,
    ATMEGARFR2_PHY_TX_PWR_TX_PWR_VALUE__2_8dBm = 0x01,
    ATMEGARFR2_PHY_TX_PWR_TX_PWR_VALUE__2_3dBm = 0x02,
    ATMEGARFR2_PHY_TX_PWR_TX_PWR_VALUE__1_8dBm = 0x03,
    ATMEGARFR2_PHY_TX_PWR_TX_PWR_VALUE__1_3dBm = 0x04,
    ATMEGARFR2_PHY_TX_PWR_TX_PWR_VALUE__0_7dBm = 0x05,
    ATMEGARFR2_PHY_TX_PWR_TX_PWR_VALUE__0dBm = 0x06,
    ATMEGARFR2_PHY_TX_PWR_TX_PWR_VALUE__m1dBm = 0x07,
    ATMEGARFR2_PHY_TX_PWR_TX_PWR_VALUE__m2dBm = 0x08,
    ATMEGARFR2_PHY_TX_PWR_TX_PWR_VALUE__m3dBm = 0x09,
    ATMEGARFR2_PHY_TX_PWR_TX_PWR_VALUE__m4dBm = 0x0A,
    ATMEGARFR2_PHY_TX_PWR_TX_PWR_VALUE__m5dBm = 0x0B,
    ATMEGARFR2_PHY_TX_PWR_TX_PWR_VALUE__m7dBm = 0x0C,
    ATMEGARFR2_PHY_TX_PWR_TX_PWR_VALUE__m9dBm = 0x0D,
    ATMEGARFR2_PHY_TX_PWR_TX_PWR_VALUE__m12dBm = 0x0E,
    ATMEGARFR2_PHY_TX_PWR_TX_PWR_VALUE__m17dBm = 0x0F,

};

enum atmegarfr2_phy_rssi {
    ATMEGARFR2_PHY_RSSI_MASK__RX_CRC_VALID = 0x80,
    ATMEGARFR2_PHY_RSSI_MASK__RND_VALUE = 0x60,
    ATMEGARFR2_PHY_RSSI_MASK__RSSI = 0x1F,
};

enum atmegarfr2_xosc_ctrl {
    ATMEGARFR2_XOSC_CTRL__XTAL_MODE_CRYSTAL = 0xF0,
    ATMEGARFR2_XOSC_CTRL__XTAL_MODE_EXTERNAL = 0xF0,
};

enum atmegarfr2_timing {
    ATMEGARFR2_TIMING__VCC_TO_P_ON = 330,
    ATMEGARFR2_TIMING__SLEEP_TO_TRX_OFF = 380,
    ATMEGARFR2_TIMING__TRX_OFF_TO_PLL_ON = 110,
    ATMEGARFR2_TIMING__TRX_OFF_TO_RX_ON = 110,
    ATMEGARFR2_TIMING__PLL_ON_TO_BUSY_TX = 16,

    ATMEGARFR2_TIMING__RESET = 100,
    ATMEGARFR2_TIMING__RESET_TO_TRX_OFF = 37,
};

enum atmegarfr2_xah_ctrl_1 {
    ATMEGARFR2_XAH_CTRL_1__AACK_FLTR_RES_FT = 0x20,
    ATMEGARFR2_XAH_CTRL_1__AACK_UPLD_RES_FT = 0x10,
    ATMEGARFR2_XAH_CTRL_1__AACK_ACK_TIME = 0x04,
    ATMEGARFR2_XAH_CTRL_1__AACK_PROM_MODE = 0x02,
};

enum atmegarfr2_csma_seed_1 {
    ATMEGARFR2_CSMA_SEED_1__AACK_SET_PD = 0x20,
    ATMEGARFR2_CSMA_SEED_1__AACK_DIS_ACK = 0x10,
    ATMEGARFR2_CSMA_SEED_1__AACK_I_AM_COORD = 0x08,
};

#ifdef __cplusplus
}
#endif
#endif /* AT86ATMEGARFR2_SETTINGS_H */
